// src/styles/screens/AlertScreen.styles.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#020617' },
  scrollContent: { padding: 20, paddingBottom: 40 },
  iconWrap: { alignItems: 'center', marginTop: 40, marginBottom: 32 },
  glowCircle: { position: 'absolute', width: 140, height: 140, borderRadius: 70, backgroundColor: '#ef4444' },
  pulseCircle: { width: 100, height: 100, borderRadius: 50, backgroundColor: 'rgba(239,68,68,0.2)', borderWidth: 4, borderColor: 'rgba(239,68,68,0.4)', alignItems: 'center', justifyContent: 'center' },
  pulseEmoji: { fontSize: 44 },
  card: { backgroundColor: 'rgba(15,23,42,0.9)', borderWidth: 1, borderColor: 'rgba(239,68,68,0.3)', borderRadius: 20, padding: 20, marginBottom: 16 },
  priorityBadgeWrap: { alignItems: 'center', marginBottom: 16 },
  priorityBadge: { backgroundColor: 'rgba(239,68,68,0.1)', borderWidth: 1, borderColor: 'rgba(239,68,68,0.3)', borderRadius: 100, paddingHorizontal: 16, paddingVertical: 6 },
  priorityText: { color: '#f87171', fontSize: 12, fontWeight: '700', letterSpacing: 1 },
  alertTitle: { color: '#fff', fontSize: 22, fontWeight: '800', textAlign: 'center', marginBottom: 8 },
  alertSubtitle: { color: '#94a3b8', fontSize: 13, textAlign: 'center', marginBottom: 20 },
  detailRow: { flexDirection: 'row', gap: 12, padding: 12, backgroundColor: 'rgba(30,41,59,0.5)', borderRadius: 12, marginBottom: 10 },
  detailIcon: { fontSize: 20, marginTop: 2 },
  detailTitle: { color: '#fff', fontWeight: '600', fontSize: 13 },
  detailBody: { color: '#cbd5e1', fontSize: 13, marginTop: 2 },
  detailSub: { color: '#64748b', fontSize: 11, marginTop: 2 },
  recsBox: { backgroundColor: 'rgba(234,179,8,0.1)', borderWidth: 1, borderColor: 'rgba(234,179,8,0.25)', borderRadius: 12, padding: 14, marginTop: 4, marginBottom: 20 },
  recsTitle: { color: '#fbbf24', fontWeight: '600', fontSize: 13, marginBottom: 8 },
  recItem: { color: '#cbd5e1', fontSize: 12, marginBottom: 4 },
  primaryBtn: { height: 50, backgroundColor: '#dc2626', borderRadius: 12, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, marginBottom: 10 },
  primaryBtnText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  secondaryBtn: { height: 50, borderWidth: 1, borderColor: '#334155', borderRadius: 12, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
  secondaryBtnText: { color: '#94a3b8', fontWeight: '600', fontSize: 15 },
  dismissBtn: { alignItems: 'center', paddingVertical: 12 },
  dismissText: { color: '#64748b', fontSize: 14 },
  source: { marginTop: 8, alignItems: 'center' },
  sourceText: { color: '#334155', fontSize: 11 },
  sourceText2: { color: '#1e293b', fontSize: 11, marginTop: 2 },
});
