// src/styles/screens/AlertScreen.styles.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#fff1d6', minHeight: '100vh' },
  scrollContent: { padding: 20, paddingBottom: 40, minHeight:'100vh' },
  iconWrap: { alignItems: 'center', marginTop: 40, marginBottom: 50 },
  glowCircle: { position: 'absolute', width: 140, height: 140, borderRadius: 70, backgroundColor: '#dc2626' },
  pulseCircle: { width: 100, height: 100, borderRadius: 50, backgroundColor: 'rgba(239,68,68,0.2)', borderWidth: 4, borderColor: 'rgba(239,68,68,0.4)', top: 18, alignItems: 'center', justifyContent: 'center' },
  pulseEmoji: { fontSize: 44 },
  card: { backgroundColor: '#f8fafc', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 16, elevation: 6, borderRadius: 20, padding: 20, marginBottom: 16 },
  priorityBadgeWrap: { alignItems: 'center', marginBottom: 16 },
  priorityBadge: { backgroundColor: 'rgba(239,68,68,0.1)', borderWidth: 1, borderColor: 'rgba(239,68,68,0.3)', borderRadius: 100, paddingHorizontal: 16, paddingVertical: 6 },
  priorityText: { color: '#f87171', fontSize: 12, fontWeight: '700', letterSpacing: 1 },
  alertTitle: { color: '#dc2626', fontSize: 22, fontWeight: '800', textAlign: 'center', marginBottom: 8 },
  alertSubtitle: { color: '#f8fafc', fontSize: 13, textAlign: 'center', marginBottom: 20 },
  detailRowWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 10 },
  detailRow: { flex: 1, padding: 12, backgroundColor: '#f8fafc', borderRadius: 12, borderWidth: 2, borderColor: '#ec7742' },
  detailIcon: { fontSize: 20, marginTop: 2 },
  detailTitle: { color: '#000', fontWeight: '600', fontSize: 13 },
  detailBody: { color: '#6d7175', fontSize: 13, marginTop: 2 },
  detailSub: { color: '#6d7175', fontSize: 11, marginTop: 2 },
  recsBox: { backgroundColor: '#ec7742', borderWidth: 2, borderColor: '#ec7742', borderRadius: 12, padding: 14, marginTop: 4, marginBottom: 20 },
  recsTitle: { color: '#000', fontWeight: '600', fontSize: 13, marginBottom: 8 },
  recItem: { color: '#000', fontSize: 12, marginBottom: 4 },
  primaryBtn: { height: 50, backgroundColor: '#dc2626', borderRadius: 12, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, marginBottom: 10 },
  primaryBtnText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  dismissBtn: { alignItems: 'center', paddingVertical: 12 },
  dismissText: { color: '#64748b', fontSize: 14 },
  source: { marginTop: 8, alignItems: 'center' },
  sourceText: { color: '#334155', fontSize: 11 },
  sourceText2: { color: '#1e293b', fontSize: 11, marginTop: 2 },
});
