// src/styles/screens/ARModeScreen.styles.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#2f3a4c', minHeight: '100vh' },
  cameraBg: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: '#f8fafc', opacity: 0.5 },
  safeArea: { flex: 1 },
  topHeader: { padding: 16, backgroundColor: '#fff1d6' },
  topHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  exitBtn: { borderRadius: 10, paddingHorizontal: 12, paddingVertical: 7 },
  exitBtnText: { color: '#000', fontSize: 14 },
  arBadge: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    backgroundColor: '#f8fafc', borderWidth: 2,
    borderColor: '#dc2626', borderRadius: 100,
    paddingHorizontal: 12, paddingVertical: 6,
  },
  arBadgeText: { color: '#000', fontWeight: '600', fontSize: 13 },
  cameraHint: {
    width: '25.5%', backgroundColor: 'rgba(15,23,42,0.6)', borderWidth: 1,
    borderColor: 'rgba(51,65,85,0.6)', borderRadius: 10, padding: 10,
    flexDirection: 'row', alignItems: 'center', gap: 8,
  },
  cameraHintText: { color: '#fff', fontSize: 13 },
  dangerBanner: {
    width: '25%', marginLeft: 16, marginTop: 20,
    backgroundColor: 'rgba(239,68,68,0.6)', borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.4)', borderRadius: 10, padding: 10,
    flexDirection: 'row', alignItems: 'center', gap: 8,
  },
  dangerDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#ef4444' },
  dangerText: { color: '#f8fafc', fontSize: 12, fontWeight: '600', flex: 1 },
  arCenter: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  distanceCard: {
    position: 'absolute', top: 10,
    backgroundColor: 'rgba(15,23,42,0.9)', borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.4)', borderRadius: 16,
    paddingHorizontal: 24, paddingVertical: 16,
  },
  distanceLabel: { color: '#60a5fa', fontSize: 12, textAlign: 'center', marginBottom: 2 },
  distanceValue: { color: '#fff', fontSize: 42, fontWeight: '800', textAlign: 'center' },
  distanceUnit: { color: '#64748b', fontSize: 12, textAlign: 'center' },
  arrowCircle: {
    width: 100, height: 100, borderRadius: 50,
    backgroundColor: 'rgba(59,130,246,0.2)', borderWidth: 4, borderColor: '#3b82f6',
    alignItems: 'center', justifyContent: 'center',
  },
  arrowText: { fontSize: 48, color: '#fff' },
  sideMarkerLeft: { position: 'absolute', left: 24 },
  sideMarkerRight: { position: 'absolute', right: 24 },
  sideMarkerBar: { width: 4, height: 80, backgroundColor: 'rgba(59,130,246,0.6)', borderRadius: 2 },
  speedCard: {
    position: 'absolute', bottom: 240, left: 16,
    backgroundColor: 'rgba(15,23,42,0.8)', borderWidth: 1,
    borderColor: '#334155', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8,
  },
  speedLabel: { color: '#fff', fontSize: 10 },
  speedValue: { color: '#fff', fontSize: 20, fontWeight: '800' },
  speedUnit: { fontSize: 12, color: '#64748b' },
  compass: {
    position: 'absolute', top: 130, right: 16,
    backgroundColor: 'rgba(15,23,42,0.8)', borderWidth: 1,
    borderColor: '#334155', borderRadius: 100,
    width: 52, height: 52, alignItems: 'center', justifyContent: 'center',
  },
  compassN: { color: '#ef4444', fontSize: 10, fontWeight: '700' },
  bottomPanel: { padding: 16, gap: 10, backgroundColor: '#fff1d6' },
  safeZoneCard: {
    borderWidth: 2, borderColor: 'rgba(236, 119, 66, 0.4)',
    backgroundColor: 'rgba(236, 119, 66, 0.6)', borderRadius: 14,
    padding: 14, flexDirection: 'row', alignItems: 'center', gap: 10,
  },
  safeZoneIcon: {
    width: 36, height: 36, borderRadius: 18,
    backgroundColor: 'rgba(236, 119, 66, 0.3)', alignItems: 'center', justifyContent: 'center',
  },
  safeZoneTitle: { color: '#fff', fontWeight: '600', fontSize: 14 },
  safeZoneSub: { color: '#fff', fontSize: 12 },
  instructionCard: {
    backgroundColor: 'rgba(15,23,42,0.9)', borderWidth: 1,
    borderColor: '#1e293b', borderRadius: 14, padding: 14,
    flexDirection: 'row', alignItems: 'flex-start', gap: 10,
  },
  instructionIcon: {
    width: 36, height: 36, borderRadius: 18,
    backgroundColor: 'rgba(59,130,246,0.2)', alignItems: 'center', justifyContent: 'center',
  },
  instructionTitle: { color: '#fff', fontWeight: '600', fontSize: 14, marginBottom: 2 },
  instructionBody: { color: '#fff', fontSize: 12 },
  instructionNext: { color: '#fff', fontSize: 11, marginTop: 4 },
  tipRow: { alignItems: 'center', paddingVertical: 4 },
  tipText: { color: '#475569', fontSize: 12 },
});
