// src/styles/screens/ARModeScreen.styles.js
import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  webContainer: {
    position: 'fixed',
    inset: 0,
    backgroundColor: '#000',
    zIndex: 9999,
    display: 'flex',
    flexDirection: 'column',
  },
  nativeCamera: {
    ...Platform.select({
      ios: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
      android: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
      default: {},
    }),
  },
  video: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  loadingOverlay: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.72)',
    zIndex: 40,
  },
  loadingOnly: {
    flex: 1,
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    color: '#fff',
    marginTop: 12,
    fontSize: 14,
    fontWeight: '600',
  },
  topBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    paddingTop: 20,
    background:
      Platform.OS === 'web'
        ? 'linear-gradient(to bottom, rgba(0,0,0,0.72) 0%, transparent 100%)'
        : 'rgba(0,0,0,0.35)',
    zIndex: 30,
    display: 'flex',
  },
  backBtn: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  backBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(220,38,38,0.88)',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    display: 'flex',
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#fff',
  },
  badgeText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  compassChip: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  compassText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
    fontFamily: 'monospace',
  },
  centerGuideWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    top: '26%',
    alignItems: 'center',
    zIndex: 25,
  },
  arrowBadge: {
    width: 128,
    height: 128,
    borderRadius: 64,
    backgroundColor: 'rgba(220,38,38,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.22)',
    shadowColor: '#DC2626',
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 10,
  },
  arrowText: {
    fontSize: 64,
    lineHeight: 72,
  },
  mainCard: {
    marginTop: 18,
    width: '100%',
    maxWidth: 520,
    backgroundColor: 'rgba(0,0,0,0.58)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  mainInstruction: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
  },
  subInstruction: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 13,
    marginTop: 8,
    textAlign: 'center',
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    padding: 20,
    background:
      Platform.OS === 'web'
        ? 'linear-gradient(to top, rgba(0,0,0,0.84) 0%, transparent 100%)'
        : 'rgba(0,0,0,0.48)',
    zIndex: 30,
  },
  infoRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
    display: 'flex',
  },
  infoChip: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderWidth: 1,
    borderColor: 'rgba(220,38,38,0.4)',
    borderRadius: 12,
    padding: 10,
  },
  infoLabel: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 1.2,
    fontFamily: 'monospace',
  },
  infoValue: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
    marginTop: 2,
  },
  hintRow: {
    alignItems: 'center',
    display: 'flex',
  },
  hintText: {
    color: 'rgba(255,255,255,0.76)',
    fontSize: 13,
    textAlign: 'center',
  },
  permDenied: {
    flex: 1,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  permTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 10,
  },
  permDesc: {
    color: '#94a3b8',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 30,
  },
  exitBtnSolid: {
    backgroundColor: '#DC2626',
    borderRadius: 12,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  exitBtnSolidText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
  },
  fallback: {
    flex: 1,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  fallbackText: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
  },
  fallbackBtn: {
    marginTop: 20,
    backgroundColor: '#DC2626',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 10,
  },
  fallbackBtnText: {
    color: '#fff',
    fontWeight: '700',
  },
  missingRouteWrap: {
    flex: 1,
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
  },
  missingRouteTitle: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 12,
  },
  missingRouteText: {
    color: '#94a3b8',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 22,
  },
});
