// src/styles/screens/EvacuationScreen.styles.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f8fafc' },
  header: { backgroundColor: '#dc2626', borderBottomWidth: 1, borderBottomColor: '#dc2626', padding: 16 },
  headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  backText: { color: '#f8fafc', fontSize: 14 },
  navBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(255,255,255,1)', borderWidth: 1, borderColor: 'rgba(59,130,246,0.25)', borderRadius: 100, paddingHorizontal: 10, paddingVertical: 4 },
  navBadgeText: { color: '#000', fontSize: 12, fontWeight: '600' },
  headerTitle: { color: '#fff', fontSize: 20, fontWeight: '800' },
  headerSub: { color: 'rgba(255,255,255,0.8)', fontSize: 13 },
  mapArea: { height: 180, backgroundColor: '#cbd1d2', alignItems: 'center', justifyContent: 'center' },
  mapOverlay: { position: 'absolute', bottom: 16, alignSelf: 'center', backgroundColor: '#dc2626', borderWidth: 1, borderColor: '#dc2626', borderRadius: 100, paddingHorizontal: 16, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 8 },
  mapOverlayText: { color: '#f8fafc', fontSize: 13, fontWeight: '600' },
  locationDot: { width: 16, height: 16, borderRadius: 8, backgroundColor: '#3b82f6', borderWidth: 2, borderColor: '#000' },
  destinationDot: { position: 'absolute', top: 16, right: 32, width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(0,0,0,0)', borderWidth: 2, borderColor: 'rgba(0,0,0,0)', alignItems: 'center', justifyContent: 'center' },
  mapLabel: { color: '#000', fontSize: 13 },
  routesSection: { padding: 16, borderBottomWidth: 1, borderBottomColor: '#f8fafc' },
  routesHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  routesTitle: { color: '#000', fontWeight: '600', fontSize: 14 },
  arModeBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, borderWidth: 1.5, borderColor: '#dc2626', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 5 },
  arModeBtnText: { color: '#dc2626', fontSize: 12, fontWeight: '600' },
  routeCard: { padding: 12, borderRadius: 12, marginBottom: 8, borderWidth: 1 },
  routeCardActive: { backgroundColor: 'rgba(59,130,246,0.1)', borderColor: '#3b82f6' },
  routeCardInactive: { backgroundColor: 'rgba(30,41,59,0.5)', borderColor: '#334155' },
  routeCardTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  routeName: { color: '#000', fontWeight: '600', fontSize: 14 },
  routeStatusClear: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, borderWidth: 1, backgroundColor: 'rgba(16,185,129,0.1)', borderColor: 'rgba(16,185,129,0.3)' },
  routeStatusCaution: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, borderWidth: 1, backgroundColor: 'rgba(234,179,8,0.1)', borderColor: 'rgba(234,179,8,0.3)' },
  routeStatusClearText: { fontSize: 11, fontWeight: '600', color: '#34d399' },
  routeStatusCautionText: { fontSize: 11, fontWeight: '600', color: '#fbbf24' },
  routeMeta: { color: '#64748b', fontSize: 12 },
  routeDesc: { color: '#475569', fontSize: 11, marginTop: 2 },
  directionsSection: { padding: 16 },
  directionsHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  directionsTitle: { color: '#000', fontWeight: '600', fontSize: 14 },
  voiceBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, borderWidth: 1 },
  voiceBtnOn: { backgroundColor: '#dc2626', borderColor: '#dc2626' },
  voiceBtnOff: { backgroundColor: '#f8fafc', borderColor: '#f8fafc' },
  voiceBtnTextOn: { color: '#f8fafc', fontSize: 12 },
  voiceBtnTextOff: { color: '#000', fontSize: 12 },
  stepRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  stepCol: { alignItems: 'center' },
  stepNum: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  stepNumActive: { backgroundColor: '#dc2626' },
  stepNumInactive: { backgroundColor: '#000' },
  stepNumTextActive: { color: '#f8fafc', fontWeight: '700', fontSize: 13 },
  stepNumTextInactive: { color: '#f8fafc', fontWeight: '700', fontSize: 13 },
  stepLine: { width: 1, flex: 1, backgroundColor: '#000', marginVertical: 2 },
  stepCard: { flex: 1, backgroundColor: '#f8fafc', borderWidth: 1.5, borderColor: '#dc2626', borderRadius: 12, padding: 12, marginBottom: 4 },
  stepInstruction: { color: '#000', fontSize: 13, marginBottom: 6 },
  stepMeta: { color: '#475569', fontSize: 11 },
  safeZoneBox: { backgroundColor: '#f8fafc', borderWidth: 1.5, borderColor: '#dc2626', borderRadius: 12, padding: 16, marginTop: 4 },
  safeZoneRow: { flexDirection: 'row', gap: 10 },
  safeZoneTitle: { color: '#000', fontWeight: '600', fontSize: 14 },
  safeZoneName: { color: '#475569', fontSize: 13, marginTop: 2 },
  safeZoneSub: { color: '#475569', fontSize: 11, marginTop: 2 },
  footer: { padding: 16, borderTopWidth: 1, borderTopColor: '#fff', backgroundColor: '#f8fafc' },
  startBtn: { height: 52, backgroundColor: '#dc2626', borderRadius: 14, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
  startBtnText: { color: '#f8fafc', fontWeight: '700', fontSize: 16 },
});
