// src/styles/screens/EvacuationScreen.styles.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#020617' },
  header: { backgroundColor: '#0f172a', borderBottomWidth: 1, borderBottomColor: '#1e293b', padding: 16 },
  headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  backText: { color: '#94a3b8', fontSize: 14 },
  navBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(59,130,246,0.1)', borderWidth: 1, borderColor: 'rgba(59,130,246,0.25)', borderRadius: 100, paddingHorizontal: 10, paddingVertical: 4 },
  navBadgeText: { color: '#60a5fa', fontSize: 12, fontWeight: '600' },
  headerTitle: { color: '#fff', fontSize: 20, fontWeight: '800' },
  headerSub: { color: '#64748b', fontSize: 13 },
  mapArea: { height: 180, backgroundColor: '#1e293b', alignItems: 'center', justifyContent: 'center' },
  mapOverlay: { position: 'absolute', bottom: 16, alignSelf: 'center', backgroundColor: 'rgba(15,23,42,0.9)', borderWidth: 1, borderColor: '#334155', borderRadius: 100, paddingHorizontal: 16, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 8 },
  mapOverlayText: { color: '#fff', fontSize: 13, fontWeight: '600' },
  locationDot: { width: 16, height: 16, borderRadius: 8, backgroundColor: '#3b82f6', borderWidth: 3, borderColor: '#fff' },
  destinationDot: { position: 'absolute', top: 16, right: 32, width: 32, height: 32, borderRadius: 16, backgroundColor: '#10b981', borderWidth: 3, borderColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  mapLabel: { color: '#334155', fontSize: 13 },
  routesSection: { padding: 16, borderBottomWidth: 1, borderBottomColor: '#1e293b' },
  routesHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  routesTitle: { color: '#fff', fontWeight: '600', fontSize: 14 },
  arModeBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, borderWidth: 1, borderColor: '#8b5cf6', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 5 },
  arModeBtnText: { color: '#a78bfa', fontSize: 12, fontWeight: '600' },
  routeCard: { padding: 12, borderRadius: 12, marginBottom: 8, borderWidth: 1 },
  routeCardActive: { backgroundColor: 'rgba(59,130,246,0.1)', borderColor: '#3b82f6' },
  routeCardInactive: { backgroundColor: 'rgba(30,41,59,0.5)', borderColor: '#334155' },
  routeCardTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  routeName: { color: '#fff', fontWeight: '600', fontSize: 14 },
  routeStatusClear: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, borderWidth: 1, backgroundColor: 'rgba(16,185,129,0.1)', borderColor: 'rgba(16,185,129,0.3)' },
  routeStatusCaution: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, borderWidth: 1, backgroundColor: 'rgba(234,179,8,0.1)', borderColor: 'rgba(234,179,8,0.3)' },
  routeStatusClearText: { fontSize: 11, fontWeight: '600', color: '#34d399' },
  routeStatusCautionText: { fontSize: 11, fontWeight: '600', color: '#fbbf24' },
  routeMeta: { color: '#64748b', fontSize: 12 },
  routeDesc: { color: '#475569', fontSize: 11, marginTop: 2 },
  directionsSection: { padding: 16 },
  directionsHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  directionsTitle: { color: '#fff', fontWeight: '600', fontSize: 14 },
  voiceBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, borderWidth: 1 },
  voiceBtnOn: { backgroundColor: 'rgba(59,130,246,0.15)', borderColor: 'rgba(59,130,246,0.4)' },
  voiceBtnOff: { backgroundColor: 'rgba(30,41,59,0.5)', borderColor: '#334155' },
  voiceBtnTextOn: { color: '#60a5fa', fontSize: 12 },
  voiceBtnTextOff: { color: '#64748b', fontSize: 12 },
  stepRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  stepCol: { alignItems: 'center' },
  stepNum: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  stepNumActive: { backgroundColor: '#3b82f6' },
  stepNumInactive: { backgroundColor: '#1e293b' },
  stepNumTextActive: { color: '#fff', fontWeight: '700', fontSize: 13 },
  stepNumTextInactive: { color: '#64748b', fontWeight: '700', fontSize: 13 },
  stepLine: { width: 1, flex: 1, backgroundColor: '#1e293b', marginVertical: 2 },
  stepCard: { flex: 1, backgroundColor: 'rgba(30,41,59,0.5)', borderWidth: 1, borderColor: '#1e293b', borderRadius: 12, padding: 12, marginBottom: 4 },
  stepInstruction: { color: '#fff', fontSize: 13, marginBottom: 6 },
  stepMeta: { color: '#475569', fontSize: 11 },
  safeZoneBox: { backgroundColor: 'rgba(16,185,129,0.1)', borderWidth: 1, borderColor: 'rgba(16,185,129,0.25)', borderRadius: 12, padding: 16, marginTop: 4 },
  safeZoneRow: { flexDirection: 'row', gap: 10 },
  safeZoneTitle: { color: '#fff', fontWeight: '600', fontSize: 14 },
  safeZoneName: { color: '#cbd5e1', fontSize: 13, marginTop: 2 },
  safeZoneSub: { color: '#64748b', fontSize: 11, marginTop: 2 },
  footer: { padding: 16, borderTopWidth: 1, borderTopColor: '#1e293b', backgroundColor: '#0f172a' },
  startBtn: { height: 52, backgroundColor: '#2563eb', borderRadius: 14, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
  startBtnText: { color: '#fff', fontWeight: '700', fontSize: 16 },
});
