// src/styles/screens/LoginScreen.styles.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#fff7ed' },
  keyboardView: { flex: 1 },
  scrollContent: { padding: 20, paddingBottom: 40 },
  header: { alignItems: 'center', marginTop: 20, marginBottom: 32 },
  logoContainer: { width: 72, height: 72, backgroundColor: '#ef4444', borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginBottom: 16, shadowColor: '#ef4444', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.4, shadowRadius: 16, elevation: 12 },
  logoEmoji: { fontSize: 36 },
  appName: { fontSize: 36, fontWeight: '800', color: '#dc2626', letterSpacing: -1 },
  tagline: { fontSize: 15, color: '#475569', marginTop: 4, fontWeight: '500' },
  subtitle: { fontSize: 12, color: '#94a3b8', marginTop: 4 },
  card: { backgroundColor: 'rgba(255,255,255,0.9)', borderRadius: 24, padding: 24, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.15, shadowRadius: 20, elevation: 10 },
  sectionTitle: { fontSize: 20, fontWeight: '700', color: '#1e293b', marginBottom: 16 },
  rolesContainer: { gap: 12, marginBottom: 24 },
  roleCard: { padding: 16, borderRadius: 16, borderWidth: 2, flexDirection: 'row', alignItems: 'center', gap: 12 },
  roleCardDefault: { borderColor: '#e2e8f0', backgroundColor: '#f8fafc' },
  roleIconContainer: { width: 44, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  roleIconBgDefault: { backgroundColor: '#f1f5f9' },
  roleEmoji: { fontSize: 22 },
  roleName: { fontSize: 15, fontWeight: '700', color: '#1e293b' },
  roleDesc: { fontSize: 12, color: '#64748b', marginTop: 2 },
  checkmark: { fontSize: 18, color: '#dc2626' },
  inputLabel: { fontSize: 13, fontWeight: '600', color: '#374151', marginBottom: 6 },
  input: { height: 48, borderWidth: 1.5, borderColor: '#cbd5e1', borderRadius: 12, paddingHorizontal: 14, fontSize: 15, color: '#1e293b', backgroundColor: '#fff', marginBottom: 16 },
  privacyBox: { backgroundColor: '#eff6ff', borderWidth: 2, borderColor: '#bfdbfe', borderRadius: 16, padding: 16, marginBottom: 20 },
  privacyHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  privacyTitle: { fontSize: 15, fontWeight: '700', color: '#1e293b' },
  privacyItem: { flexDirection: 'row', gap: 8, marginBottom: 6 },
  privacyCheck: { color: '#2563eb', marginTop: 1 },
  privacyItemText: { fontSize: 12, color: '#334155', flex: 1 },
  consentRow: { flexDirection: 'row', gap: 10, alignItems: 'flex-start', backgroundColor: 'rgba(255,255,255,0.6)', borderRadius: 12, padding: 12, marginTop: 8 },
  checkbox: { width: 20, height: 20, borderRadius: 6, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  checkboxChecked: { borderColor: '#2563eb', backgroundColor: '#2563eb' },
  checkboxUnchecked: { borderColor: '#94a3b8', backgroundColor: 'transparent' },
  checkboxTick: { color: '#fff', fontSize: 12 },
  consentText: { fontSize: 12, color: '#374151', flex: 1, lineHeight: 18 },
  trustBadges: { flexDirection: 'row', justifyContent: 'center', gap: 24, marginBottom: 20 },
  trustBadge: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  trustIcon: { width: 32, height: 32, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  trustLabel: { fontSize: 12, fontWeight: '600' },
  trustSub: { fontSize: 10 },
  loginBtn: { height: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  loginBtnActive: { backgroundColor: '#dc2626', shadowColor: '#dc2626', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.4, shadowRadius: 12, elevation: 8 },
  loginBtnDisabled: { backgroundColor: '#fca5a5' },
  loginBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  footer: { fontSize: 11, color: '#94a3b8', textAlign: 'center', marginTop: 12 },
});
