// src/styles/screens/ResponderCommandView.styles.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#020617' },
  header: {
    backgroundColor: '#0f172a', borderBottomWidth: 1, borderBottomColor: '#1e293b',
    padding: 16, flexDirection: 'row', alignItems: 'center',
  },
  headerIcon: { width: 40, height: 40, backgroundColor: '#dc2626', borderRadius: 10, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  headerTitle: { color: '#fff', fontSize: 16, fontWeight: '800' },
  liveRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 2 },
  liveDot: { width: 6, height: 6, borderRadius: 3 },
  liveText: { color: '#64748b', fontSize: 12 },
  tabBar: { flexDirection: 'row', backgroundColor: '#0f172a', borderBottomWidth: 1, borderBottomColor: '#1e293b' },
  tab: { flex: 1, paddingVertical: 12, alignItems: 'center', borderBottomWidth: 2 },
  tabActive: { borderBottomColor: '#ef4444' },
  tabInactive: { borderBottomColor: 'transparent' },
  tabText: { fontSize: 12, fontWeight: '600' },
  tabTextActive: { color: '#ef4444' },
  tabTextInactive: { color: '#64748b' },
  scrollContent: { padding: 16 },
  tabSubtitle: { color: '#94a3b8', fontSize: 13, marginBottom: 12 },
  unitCard: { backgroundColor: '#0f172a', borderWidth: 1, borderColor: '#1e293b', borderRadius: 16, padding: 16, marginBottom: 10 },
  unitCardTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  unitLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  unitIcon: { width: 36, height: 36, backgroundColor: '#1e293b', borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  unitName: { color: '#fff', fontWeight: '700', fontSize: 14 },
  unitType: { color: '#64748b', fontSize: 11 },
  unitStatusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  unitStatusText: { fontSize: 11, fontWeight: '600' },
  unitLocation: { color: '#475569', fontSize: 12 },
  fireCard: { backgroundColor: '#0f172a', borderWidth: 1, borderColor: '#1e293b', borderRadius: 16, padding: 16, marginBottom: 10 },
  fireCardTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  fireLocation: { color: '#fff', fontWeight: '700', fontSize: 14 },
  fireSeverityBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, backgroundColor: 'rgba(239,68,68,0.15)' },
  fireSeverityText: { color: '#f87171', fontSize: 11, fontWeight: '700' },
  fireMeta: { color: '#475569', fontSize: 12 },
  emptyBox: { backgroundColor: '#0f172a', borderRadius: 16, padding: 24, alignItems: 'center' },
  logRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  logDotCol: { alignItems: 'center' },
  logDot: { width: 8, height: 8, borderRadius: 4, marginTop: 6 },
  logLine: { width: 1, flex: 1, backgroundColor: '#1e293b', marginTop: 2 },
  logCard: {
    flex: 1, backgroundColor: '#0f172a', borderWidth: 1, borderColor: '#1e293b',
    borderRadius: 12, padding: 12, marginBottom: 4,
  },
  logCardTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  logTypeBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
  logTypeText: { fontSize: 10, fontWeight: '700' },
  logTime: { color: '#475569', fontSize: 11 },
  logMsg: { color: '#cbd5e1', fontSize: 13 },
});
