// src/styles/screens/SafetyTipsScreen.styles.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#fff7ed' },
  header: { backgroundColor: '#dc2626', padding: 20, paddingTop: 24 },
  backText: { color: 'rgba(255,255,255,0.8)', fontSize: 14, marginBottom: 12 },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 6 },
  headerIcon: { width: 48, height: 48, backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { color: '#fff', fontSize: 28, fontWeight: '800' },
  headerSub: { color: 'rgba(255,255,255,0.85)', fontSize: 14 },
  scrollContent: { padding: 16, paddingBottom: 40 },
  sectionTitle: { fontSize: 20, fontWeight: '700', color: '#0f172a', marginBottom: 14, marginTop: 4 },
  prepCard: { backgroundColor: '#fff', borderWidth: 2, borderRadius: 20, padding: 18, marginBottom: 14, boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.06)' },
  prepCardHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 14 },
  prepIconWrap: { width: 44, height: 44, backgroundColor: '#f8fafc', borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  prepCardTitle: { fontSize: 16, fontWeight: '700', color: '#0f172a' },
  prepItem: { flexDirection: 'row', gap: 8, marginBottom: 6 },
  prepCheck: { marginTop: 1 },
  prepItemText: { fontSize: 13, color: '#334155', flex: 1 },
  duringCard: { backgroundColor: '#fff', borderWidth: 2, borderColor: '#fecaca', borderRadius: 20, padding: 18, marginBottom: 14 },
  duringCardHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 14 },
  duringIconWrap: { width: 36, height: 36, backgroundColor: '#fef2f2', borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  duringCardTitle: { fontSize: 15, fontWeight: '700', color: '#0f172a' },
  duringItem: { flexDirection: 'row', gap: 8, marginBottom: 6 },
  duringBullet: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#ef4444', marginTop: 6 },
  duringItemText: { fontSize: 13, color: '#334155', flex: 1 },
  emergencyCard: { backgroundColor: '#dc2626', borderRadius: 20, padding: 20, marginBottom: 14 },
  emergencyHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 14 },
  emergencyTitle: { color: '#fff', fontWeight: '700', fontSize: 17 },
  emergencyRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  emergencyName: { color: 'rgba(255,255,255,0.9)', fontSize: 14 },
  emergencyNumBadge: { backgroundColor: '#fff', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 4 },
  emergencyNum: { color: '#dc2626', fontWeight: '800', fontSize: 14 },
  resourcesCard: { backgroundColor: '#fff', borderWidth: 2, borderColor: '#bfdbfe', borderRadius: 20, padding: 18 },
  resourcesTitle: { fontSize: 15, fontWeight: '700', color: '#0f172a', marginBottom: 12 },
  resourceItem: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  resourceCheck: { color: '#2563eb' },
  resourceText: { fontSize: 13, color: '#334155', flex: 1 },
});