// src/screens/resident/AlertScreen.js
import React, { useEffect, useRef } from 'react';
import { View, Text, TouchableOpacity, ScrollView, SafeAreaView, Animated, Easing, Platform } from 'react-native';
import styles from '../../styles/screens/AlertScreen.styles';

const DETAIL_ROWS = [
  { icon: '⏱️', title: 'Estimated Time', body: 'Fire may reach your area in 12 hours' },
  { icon: '📍', title: 'Your Location', body: 'Haifa, Northern District', sub: '2.8 km from active fire zone' },
  { icon: '⚠️', title: 'Risk Level', body: 'Moderate to High', sub: 'Wind conditions may accelerate spread' },
];

const RECOMMENDATIONS = [
  'Prepare emergency supplies and important documents',
  'Review evacuation routes and transportation options',
  'Stay informed through official channels',
  'Be ready to evacuate if conditions worsen',
];

export default function AlertScreen({ navigation }) {
  let nav = navigation;
  if (Platform.OS !== 'web') {
    try { const { useNavigation } = require('@react-navigation/native'); nav = useNavigation(); } catch {}
  }

  const pulse = useRef(new Animated.Value(1)).current;
  const glow = useRef(new Animated.Value(0.3)).current;

  useEffect(() => {
    Animated.loop(Animated.sequence([
      Animated.timing(pulse, { toValue: 1.15, duration: 900, useNativeDriver: true, easing: Easing.inOut(Easing.ease) }),
      Animated.timing(pulse, { toValue: 1, duration: 900, useNativeDriver: true, easing: Easing.inOut(Easing.ease) }),
    ])).start();
    Animated.loop(Animated.sequence([
      Animated.timing(glow, { toValue: 0.7, duration: 1000, useNativeDriver: true }),
      Animated.timing(glow, { toValue: 0.3, duration: 1000, useNativeDriver: true }),
    ])).start();
  }, []);

  return (
    <SafeAreaView style={styles.safeArea}>
      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        <View style={styles.iconWrap}>
          <Animated.View style={[styles.glowCircle, { opacity: glow }]} />
          <Animated.View style={[styles.pulseCircle, { transform: [{ scale: pulse }] }]}>
            <Text style={styles.pulseEmoji}>🔥</Text>
          </Animated.View>
        </View>

        <View style={styles.card}>
          <View style={styles.priorityBadgeWrap}>
            <View style={styles.priorityBadge}>
              <Text style={styles.priorityText}>🚨 HIGH PRIORITY ALERT</Text>
            </View>
          </View>

          <Text style={styles.alertTitle}>Fire Predicted Near Your Location</Text>
          <Text style={styles.alertSubtitle}>Based on AI analysis and current fire spread patterns</Text>

          {DETAIL_ROWS.map(item => (
            <View key={item.title} style={styles.detailRow}>
              <Text style={styles.detailIcon}>{item.icon}</Text>
              <View style={{ flex: 1 }}>
                <Text style={styles.detailTitle}>{item.title}</Text>
                <Text style={styles.detailBody}>{item.body}</Text>
                {item.sub && <Text style={styles.detailSub}>{item.sub}</Text>}
              </View>
            </View>
          ))}

          <View style={styles.recsBox}>
            <Text style={styles.recsTitle}>Recommended Actions</Text>
            {RECOMMENDATIONS.map((rec, i) => (
              <Text key={i} style={styles.recItem}>• {rec}</Text>
            ))}
          </View>

          <TouchableOpacity style={styles.primaryBtn} onPress={() => nav?.navigate('Evacuation')}>
            <Text style={{ fontSize: 18 }}>🧭</Text>
            <Text style={styles.primaryBtnText}>View Evacuation Route</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.secondaryBtn}>
            <Text style={{ fontSize: 18 }}>📤</Text>
            <Text style={styles.secondaryBtnText}>Share Location with Family</Text>
          </TouchableOpacity>
        </View>

        <TouchableOpacity style={styles.dismissBtn} onPress={() => nav?.goBack()}>
          <Text style={styles.dismissText}>✕  Dismiss Alert</Text>
        </TouchableOpacity>

        <View style={styles.source}>
          <Text style={styles.sourceText}>Alert generated by EshMagan AI at 16:45 IST</Text>
          <Text style={styles.sourceText2}>Confidence: 87% • Source: FIRE-2026-001</Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
